<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>IFJcode17</string>
		<string>IFJcode2017</string>
	</array>
	<key>name</key>
	<string>IFJcode2017</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(call|label|jump|jumpifeq|jumpifneq|jumpifeqs|jumpifneqs)(\s+)({{identifier}})</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[LGT]F@</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[LGT]F@){{identifier}}</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(move|createframe|pushframe|popframe|defvar|call|return|pushs|pops|clears|add|sub|mul|div|adds|subs|muls|divs|lt|gt|eq|lts|gts|eqs|and|or|not|ands|ors|nots|int2float|float2int|float2r2eint|float2roint|int2char|str2int|int2floats|float2ints|float2r2eints|float2roints|int2chars|str2ints|read|write|concat|strlen|getchar|setchar|type|label|jump|jumpifeq|jumpifneq|jumpifeqs|jumpifneqs|break|dprint)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((float|int)@)(-?[0-9.]+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(string@)(.*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#</string>
			<key>name</key>
			<string>punctuation.definition.comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.base_scope</string>
	<key>uuid</key>
	<string>2c23fd25-a111-407b-910a-9e5d59ea3483</string>
</dict>
</plist>
